/** Global event categories — used as Sequelize ENUM on Event.category */
const EVENT_CATEGORIES = [
  // Music & live performance
  "Concert",
  "Music Festival",
  "Live Music",
  "DJ / Electronic",
  "Classical Music",
  "Opera",
  "Musical Theatre",
  "Karaoke",
  // Comedy & theatre
  "Comedy",
  "Stand-up Comedy",
  "Theatre",
  "Drama",
  "Dance",
  "Ballet",
  "Circus",
  "Magic Show",
  // Film & media
  "Film Screening",
  "Movie Premiere",
  "Film Festival",
  "Documentary",
  "Podcast / Talk Show",
  // Art & culture
  "Art Exhibition",
  "Gallery Opening",
  "Museum Event",
  "Cultural Festival",
  "Heritage Event",
  "Literary / Book",
  "Poetry",
  // Fashion & beauty
  "Fashion Show",
  "Beauty Pageant",
  "Modeling",
  // Sports & fitness
  "Sports",
  "Football",
  "Basketball",
  "Rugby",
  "Cricket",
  "Tennis",
  "Golf",
  "Marathon",
  "Running",
  "Cycling",
  "Swimming",
  "Motorsport",
  "Combat Sports",
  "Esports",
  "Gaming Tournament",
  "Fitness",
  "Yoga",
  "Wellness",
  // Business & professional
  "Conference",
  "Summit",
  "Seminar",
  "Workshop",
  "Training",
  "Networking",
  "Trade Show",
  "Expo",
  "Career Fair",
  "Product Launch",
  "Corporate Event",
  "Team Building",
  "Investor Meetup",
  "Hackathon",
  "Startup Pitch",
  // Food & drink
  "Food Festival",
  "Wine Tasting",
  "Beer Festival",
  "Cocktail / Bar Event",
  "Restaurant Event",
  "Cooking Class",
  // Charity & social
  "Charity",
  "Fundraiser",
  "Gala",
  "Awards Ceremony",
  "Community",
  "Meetup",
  "Social Gathering",
  "Reunion",
  // Nightlife & parties
  "Nightlife",
  "Club Night",
  "Party",
  "Birthday Party",
  "Wedding",
  "Wedding Expo",
  "Bridal Show",
  // Family & kids
  "Kids & Family",
  "Kids Show",
  "School Event",
  "Graduation",
  "Education",
  // Outdoor & adventure
  "Outdoor",
  "Camping",
  "Hiking",
  "Adventure",
  "Beach Party",
  "Boat / Cruise",
  "Travel & Tourism",
  // Religious & spiritual
  "Religious",
  "Spiritual",
  "Meditation",
  // Seasonal & holidays
  "Holiday",
  "Christmas",
  "Halloween",
  "New Year",
  "Carnival",
  "Parade",
  "Fair",
  "Market",
  // Industry & niche
  "Technology",
  "Real Estate",
  "Automotive / Car Show",
  "Agriculture / Livestock",
  "Pet Show",
  "Auction",
  "Open House",
  "Health & Medical",
  "Science",
  "Political / Civic",
  "Military / Veterans",
  // Catch-all
  "Other",
];

const isValidEventCategory = (value) =>
  value != null && value !== "" && EVENT_CATEGORIES.includes(value);

module.exports = { EVENT_CATEGORIES, isValidEventCategory };
